[workspace]
members = [
    # core and tools
    "dmg-lib",
    "dmg-boot",
    "dmg-tools",

    # peripherals
    "dmg-peripheral/camera",

    # drivers
    "dmg-driver/sdl2",
    "dmg-driver/wasm",
    "dmg-driver/gl",
    "dmg-driver/rodio",

    # frontends
    "dmg-frontend/native",
    "dmg-frontend/web",
]

