[workspace]
members = [
    "dmg-lib",
    "dmg-boot",
    "dmg-tools",
    "dmg-camera",
    "dmg-driver/sdl2",
    "dmg-driver/wasm",
    "dmg-driver/gl",
    "dmg-frontend/native",
    "dmg-frontend/web",
]

